# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -s https://raw.githubusercontent.com/monch1962/crostini-init/master/crostini-init.sh | bash -
  displayName: 'Download & run script to install utilities'

